[[block]]
block = "sound"

[[block]]
block = "net"
interval = 10
format = " $icon $device "

[[block]]
block = "battery"
interval = 30
format = " $icon $percentage "
missing_format = ""

[[block]]
block = "pomodoro"
notify_cmd = "notify-send 'Pomodoro' '{msg}'"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%A %Y-%m-%d %H:%M') "
interval = 60
